name: Destroy Development Environment

on:
  pull_request:
    types: [closed]

jobs:
  get_pr_number:
    runs-on: ubuntu-latest
    outputs:
      pr_number: ${{ steps.get_pr_number.outputs.pr_number }}
    steps:
    - name: Get PR Number
      id: get_pr_number
      run: echo "pr_number=$(echo $GITHUB_REF | awk -F'/' '{print $3}')" >> "$GITHUB_OUTPUT"

  deploy_dev:
    needs: get_pr_number
    uses: ./.github/workflows/terraform-destroy.yml
    secrets: inherit
    with:
      terraform_state: dev-pr${{ needs.get_pr_number.outputs.pr_number }}
