name: Destroy Development Environment

on:
  pull_request:
    types: [closed]

jobs:
  destroy:
    runs-on: ubuntu-latest

    steps:
    - name: Get PR Number
      id: get_pr_number
      run: echo "::set-output name=pr_number::$(echo $GITHUB_REF | awk -F'/' '{print $3}')"

    - name: Call Reusable Destroy Workflow
      uses: ./.github/workflows/terraform-destroy.yml
      with:
        terraform_state: dev-pr${{ steps.get_pr_number.outputs.pr_number }}
