name: Terraform Apply

on:
  workflow_call:
    inputs:
      terraform_state:
        required: true
        type: string

jobs:
  deploy:
    runs-on: ubuntu-latest

    env:
      AWS_REGION: us-east-1
      TF_STATE_BUCKET: wsgomes-terraform-states

    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Print Terraform State
      run: echo "Terraform State -> ${{ inputs.terraform_state }}"

    - name: Set up Terraform
      uses: hashicorp/setup-terraform@v3
      with:
        terraform_version: 1.10.5

    - name: Configure AWS credentials
      uses: aws-actions/configure-aws-credentials@v4
      with:
        aws-region: ${{ env.AWS_REGION }}
        aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
        aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}

    - name: Initialize Terraform
      run: >
        terraform init
        -backend-config="bucket=${{ env.TF_STATE_BUCKET }}"
        -backend-config="key=lambda-version-cleaner/${{ inputs.terraform_state }}/terraform.tfstate"
        -backend-config="region=${{ env.AWS_REGION }}"

    - name: Apply Terraform
      run: terraform apply -auto-approve -var="aws_region=${{ env.AWS_REGION }}" -var="terraform_state=${{ inputs.terraform_state }}"
